### ISSUE TITLE
Planning to add a recipe for `element-coder` to `conda-forge`

### ISSUE THREAD

**Issue by sgbaird** [kjappelbaum/element-coder#13]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=533022&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

All dependencies of a `conda-forge` recipe [need to be hosted on `conda`](https://stackoverflow.com/questions/37541084/cant-specify-pip-dependency-in-conda-meta-yaml-file)

**Comment by kjappelbaum** [comment]
https://github.com/conda-forge/staged-recipes/pull/19628

**Comment by sgbaird** [comment]
Thanks for getting that started!

**Comment by kjappelbaum** [comment]
done
