### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by sgbaird** [kjappelbaum/element-coder#14]
Do you know what's specific to the Python > 3.8 requirement in setup.cfg? E.g. certain packages or coding conventions that you use that require 3.8+

**Comment by kjappelbaum** [comment]
I'll double-check this, but I think we can relax it to >= py3.7. 
It is due to sciris (https://github.com/sciris/sciris/issues/122#issuecomment-1183478440).
However, I'm considering dropping the sciris dependency as it makes many issues ...

**Comment by sgbaird** [comment]
Good to know! Thanks for the quick responses.

**Comment by sgbaird** [comment]
Planning to use `element-coder` within `matbench-genmetrics`. The `sciris` dependency does seem to have [quite a few requirements](https://github.com/sciris/sciris/blob/develop/setup.py). Do you think you'll keep `sciris`?

**Comment by kjappelbaum** [comment]
Let's drop it 🥴😀

**Comment by sgbaird** [comment]
😓 😅
