### ISSUE TITLE
implement `get_range` 

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/element-coder#8]
for https://github.com/sparks-baird/xtal2png/issues/80 

- given a list of elements, provide a range of the given encoding

**Comment by sgbaird** [comment]
I interpreted this as "encode the elements and then take the min and max as lower and upper bounds, respectively." Is that correct?

**Comment by kjappelbaum** [comment]
yea, it would follow the way matminer does it: Look at a bunch of structures, extract the elements you have in there, and then for the selected element encoding return the range.
